DROP TABLE LESTABLES CASCADE CONSTRAINTS;

CREATE TABLE LESTABLES
(
    NUMTABLE numeric(2) primary key,
    NOMTABLE VARCHAR(15) NOT NULL ,
    NBPLACE     numeric(2)
);

DROP TABLE SERVEUR CASCADE CONSTRAINTS;

CREATE TABLE SERVEUR
(
    NUMSERVEUR     numeric PRIMARY KEY,
    NOMSERVEUR    CHAR(20) NOT NULL,
    RUESERVEUR    CHAR(20) NOT NULL,
    CPSERVEUR    NUMERIC(5) NOT NULL,
    VILLESERVEUR    CHAR(20) NOT NULL,
    DATENSERVEUR    DATE NOT NULL
);

DROP TABLE CONSOMMATION CASCADE CONSTRAINTS;

CREATE TABLE CONSOMMATION
(
    NUMCONS        numeric(3) PRIMARY KEY,
    LIBCONS        CHAR(30) NOT NULL,
    PRIXCONS    DECIMAL(6,2) NOT NULL
);

DROP TABLE FACTURE CASCADE CONSTRAINTS;

CREATE TABLE FACTURE
(
    NUMFACTURE    NUMERIC NOT NULL,
    NUMTABLE     NUMERIC(2),
    NUMSERVEUR    NUMERIC,
    DATEFACTURE    DATE NOT NULL,
PRIMARY KEY (NUMFACTURE),
FOREIGN KEY (NUMTABLE) REFERENCES LESTABLES (NUMTABLE),
FOREIGN KEY (NUMSERVEUR) REFERENCES SERVEUR (NUMSERVEUR) 
);

DROP TABLE COMPREND CASCADE CONSTRAINTS;

CREATE TABLE COMPREND
(
    NUMFACTURE    NUMERIC NOT NULL,
    NUMCONS        NUMERIC(3) NOT NULL,
    QTE        NUMERIC(2),
PRIMARY KEY (NUMFACTURE,NUMCONS),
FOREIGN KEY (NUMFACTURE) REFERENCES FACTURE (NUMFACTURE) ,
FOREIGN KEY (NUMCONS) REFERENCES CONSOMMATION (NUMCONS) 
);
