-- tp2.sql

CREATE TABLE ETUDIANTS
(
    NUMERO NUMBER(4) CONSTRAINT NN_ETUDIANTS_NUMBER NOT NULL,
    NOM VARCHAR2(25) CONSTRAINT NN_ETUDIANTS_NOM NOT NULL,
    PRENOM VARCHAR2(25) CONSTRAINT NN_ETUDIANTS_PRENOM NOT NULL,
    SEXE CHAR(1) CONSTRAINT CK_ETUDIANTS_SEXE CHECK (SEXE IN ('F','M')),
    DATENAISSANCE DATE CONSTRAINT NN_ETUDIANTS_DATENAISSANCE NOT NULL,
    POIDS NUMBER,
    ANNEE NUMBER,
    CONSTRAINT PK_ETUDIANTS PRIMARY KEY(NUMERO)
);

ttitle 'La liste des contraintes crees, sur la table ETUDIANTS, est :';
select constraint_name from user_constraints where table_name='ETUDIANTS';

ALTER TABLE ETUDIANTS ADD CONSTRAINT CK_ETUDIANTS_ANNEE CHECK (ANNEE IN (1,2));

DROP TABLE ETUDIANTS;