drop table PERSONNES;

create table PERSONNES
(NUMERO number(7), 
NOM varchar(15), 
PRENOM varchar(15), 
DATENAISSANCE date, 
SEXE char(1), 
PERE number(7), 
MERE number(7),
constraint PK_PERSONNES primary key (NUMERO),
constraint FK_PERSONNES_PERE_PERSONNES foreign key(PERE) references PERSONNES,
constraint FK_PERSONNES_MERE_PERSONNES foreign key(MERE) references PERSONNES,
constraint CK_SEXE_PERSONNES check (SEXE in ('M', 'F')));

alter session set nls_date_format = 'dd-mm-yyyy' ;

insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE)
values (99,'LEBON','NICOLAS', '01-01-1895', 'M');
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE)
values (88,'HONNEUR','CLEMENCE', '01-01-1900', 'F');
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (1,'LEBON','MICHEL','04-08-1920','M', 99, 88);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (15,'LEBON','GABRIEL','04-08-1936','M', 99, 88);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE)
values (98,'CLEMENT','JEAN-BAPTISTE', '01-01-1890', 'M');
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE)
values (87,'GABRIEL','EVE', '01-01-1892', 'F');
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (2,'CLEMENT','EVE','13-11-1928','F', 98, 87);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE)
values (22,'CLEMENT','JEAN-BAPTISTE','13-11-1910','F', 98);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (3,'LEBON','NICOLAS','17-09-1958', 'M', 1, 2);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (33,'LEBON','ROSE','16-06-1951', 'F', 1, 2);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE)
values (34,'CLEMENT','RAOUL','01-01-1941', 'M', 22);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (55,'CLEMENT','MARIE','13-08-1978', 'F', 33, 34);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE)
values (56,'MEDECIN','LINA','22-02-2002', 'F', 55);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE)
values (77,'PARIS','LOUIS','20-03-1924', 'M');
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE)
values (78,'GATEAU','EVELYNE','20-03-1936', 'F');
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (4,'PARIS','INES','22-11-1969', 'F', 77, 78);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (76,'PARIS','AMELIA','20-10-1958', 'F', 77, 78);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, MERE)
values (75,'AMMAR','SERGES','20-10-1987', 'M', 76);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (5,'LEBON','CLEMENCE','19-06-2001', 'F', 3, 4);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (6,'LEBON','ADAM','19-06-2001', 'M', 3, 4);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (7,'LEBON','FRANCOIS','22-02-1954', 'M', 1, 2);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE)
values (9,'LEBON','FRANCOISE','01-09-1963', 'F', 15);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (8,'LEBON','MICHEL','05-09-1987', 'M', 7, 9);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (10,'LEBON','AIME','24-05-1993', 'M', 7, 9);
insert into PERSONNES(NUMERO, NOM, PRENOM, DATENAISSANCE, SEXE, PERE, MERE)
values (11,'LEBON','ALEXANDRE','16-07-1994', 'M', 7, 9);

commit;

TTITLE 'Les personnes'
set pages 100
select * from PERSONNES order by DATENAISSANCE;