CREATE TABLE ELEVES
(
    NUM_ELEVE NUMBER(4) PRIMARY KEY, -- primary key column
    NOM VARCHAR2(25) NOT NULL,
    PRENOM VARCHAR2(25) NOT NULL,
    DATE_NAISSANCE DATE NOT NULL,
    POIDS NUMBER,
    ANNEE NUMBER
);

CREATE TABLE PROFESSEURS
(
    NUM_PROF NUMBER(4) PRIMARY KEY,
    NOM VARCHAR2(25) NOT NULL,
    SPECIALITE VARCHAR2(25) NOT NULL,
    DATE_ENTREE DATE NOT NULL,
    DER_PROM VARCHAR2(25),
    SALAIRE_BASE NUMBER,
    SALAIRE_ACTUEL NUMBER
);

CREATE TABLE ACTIVITES
(
 NOM VARCHAR2(25) NOT NULL ,
 NIVEAU NUMBER NOT NULL,
 EQUIPE NUMBER,
 PRIMARY KEY(NOM, NIVEAU)
);

CREATE TABLE COURS(
    NUM_COURS NUMBER(4) PRIMARY KEY,
    NOM VARCHAR2(25) NOT NULL,
    NBHEURES NUMBER NOT NULL,
    ANNEE NUMBER(4) NOT NULL
);

CREATE TABLE RESULTATS 
(
    NUM_ELEVE NUMBER(4) NOT NULL,
    NUM_COURS NUMBER(4) NOT NULL,
    POINTS NUMBER NOT NULL,
    PRIMARY KEY(NUM_ELEVE, NUM_COURS)
);

CREATE TABLE CHARGE
(
    NUM_PROF NUMBER(4) NOT NULL,
    NUM_COURS NUMBER(4) NOT NULL,
    PRIMARY KEY(NUM_PROF, NUM_COURS)
);

CREATE TABLE ACTIVITES_PRATIQUEES(
    NUM_ELEVE NUMBER(4) NOT NULL,
    NIVEAU NUMBER NOT NULL,
    NOM VARCHAR2 NOT NULL,
    PRIMARY KEY(NUM_ELEVE, NIVEAU, NOM)
);

DROP TABLE 

