CREATE TABLE ELEVES
(
    NUM_ELEVE NUMBER(4) PRIMARY KEY,
    NOM VARCHAR2(25) NOT NULL,
    PRENOM VARCHAR2(25) NOT NULL,
    DATE_NAISSANCE DATE NOT NULL,
    POIDS NUMBER,
    ANNEE NUMBER
);

CREATE TABLE PROFESSEURS
(
    NUM_PROF NUMBER(4) PRIMARY KEY,
    NOM VARCHAR2(25) NOT NULL,
    SPECIALITE VARCHAR2(25) NOT NULL,
    DATE_ENTREE DATE NOT NULL,
    DER_PROM VARCHAR2(25),
    SALAIRE_BASE NUMBER,
    SALAIRE_ACTUEL NUMBER
);

CREATE TABLE ACTIVITES
(
 NOM VARCHAR2(25) NOT NULL ,
 NIVEAU NUMBER NOT NULL,
 EQUIPE NUMBER,
 PRIMARY KEY(NOM, NIVEAU)
);

CREATE TABLE COURS(
    NUM_COURS NUMBER(4) PRIMARY KEY,
    NOM VARCHAR2(25) NOT NULL,
    NBHEURES NUMBER NOT NULL,
    ANNEE NUMBER(4) NOT NULL
);

CREATE TABLE RESULTATS 
(
    NUM_ELEVE NUMBER(4) NOT NULL,
    NUM_COURS NUMBER(4) NOT NULL,
    POINTS NUMBER NOT NULL,
    PRIMARY KEY(NUM_ELEVE, NUM_COURS),
    CONSTRAINT fk_num_resultats_eleves FOREIGN KEY(NUM_ELEVE) REFERENCES ELEVES(NUM_ELEVE),
    CONSTRAINT fk_num_resultats_cours FOREIGN KEY(NUM_COURS) REFERENCES COURS(NUM_COURS)
);

CREATE TABLE CHARGE
(
    NUM_PROF NUMBER(4) NOT NULL,
    NUM_COURS NUMBER(4) NOT NULL,
    PRIMARY KEY(NUM_PROF, NUM_COURS),
    CONSTRAINT fk_num_charge_professeurs FOREIGN KEY(NUM_PROF) REFERENCES PROFESSEURS(NUM_PROF),    
    CONSTRAINT fk_num_charge_cours FOREIGN KEY(NUM_COURS) REFERENCES COURS(NUM_COURS)
);

CREATE TABLE ACTIVITES_PRATIQUEES(
    NUM_ELEVE NUMBER(4) NOT NULL,
    NIVEAU NUMBER NOT NULL,
    NOM VARCHAR2(25) NOT NULL,
    PRIMARY KEY(NUM_ELEVE, NIVEAU, NOM),
    CONSTRAINT fk_num_activitesP_eleves FOREIGN KEY(NUM_ELEVE) REFERENCES ELEVES(NUM_ELEVE),
    CONSTRAINT fk_num_activitesP_activites FOREIGN KEY(NOM,NIVEAU) REFERENCES ACTIVITES(NOM,NIVEAU)
);




DROP TABLE ELEVES CASCADE CONSTRAINT;
DROP TABLE COURS CASCADE CONSTRAINT;
DROP TABLE PROFESSEURS CASCADE CONSTRAINT;
DROP TABLE ACTIVITES CASCADE CONSTRAINT;
DROP TABLE RESULTATS CASCADE CONSTRAINT;
DROP TABLE CHARGE CASCADE CONSTRAINT;
DROP TABLE ACTIVITES_PRATIQUEES CASCADE CONSTRAINT;

