INSERT INTO SERIE VALUES(1, 'The Witcher', '01/01/2019', 'Etats-Unis', '22/12/19');
INSERT INTO SERIE VALUES(2, 'Oz', '01/01/1997', 'Etats-Unis', '12/07/1997');
INSERT INTO SERIE VALUES(3, 'Le Bureau Des Legendes', '01/01/2015', 'France', '24/04/2015');
INSERT INTO SERIE VALUES(4, 'Platane', '01/01/2011', 'France', '05/09/2011');
INSERT INTO SERIE VALUES(5, 'Mr. Robot', '01/01/2015', 'Etats-Unis', '24/06/2015');
INSERT INTO SERIE VALUES(6, 'Vinland Saga', '01/01/2019', 'Japon', '08/07/2019');
INSERT INTO SERIE VALUES(7, 'Cowboy Bebop', '01/01/1998', 'Japon', '03/04/1998');
INSERT INTO SERIE VALUES(8, 'Rick et Morty', '01/01/2013', 'Etats-Unis', '02/12/2013');
INSERT INTO SERIE VALUES(9, 'Futurama', '01/01/1999', 'Etats-Unis', '28/03/2013');
INSERT INTO SERIE VALUES(10, 'The Pacific', '01/01/2010', 'Etats-Unis', '14/03/2010');
INSERT INTO SERIE VALUES(11, 'Animaniacs', '01/01/1993', 'Etats-Unis', '13/09/1993');


INSERT INTO GENRE VALUES(1, 'Comédie');
INSERT INTO GENRE VALUES(2, 'Drame');
INSERT INTO GENRE VALUES(3, 'Science-Fiction');
INSERT INTO GENRE VALUES(4, 'Fantasy');
INSERT INTO GENRE VALUES(5, 'Medieval');
INSERT INTO GENRE VALUES(6, 'Espionnage');
INSERT INTO GENRE VALUES(7, 'Sitcom');
INSERT INTO GENRE VALUES(8, 'Thriller');
INSERT INTO GENRE VALUES(9, 'Historique');
INSERT INTO GENRE VALUES(10, 'Action');
INSERT INTO GENRE VALUES(11, 'Aventure');
INSERT INTO GENRE VALUES(12, 'Animation');
INSERT INTO GENRE VALUES(13, 'Guerre');
INSERT INTO GENRE VALUES(14, 'Biopic');


INSERT INTO DE VALUES(1, 4);
INSERT INTO DE VALUES(1, 5);

INSERT INTO DE VALUES(2, 2);

INSERT INTO DE VALUES(3, 6);

INSERT INTO DE VALUES(4, 1);
INSERT INTO DE VALUES(4, 7);

INSERT INTO DE VALUES(5, 2);
INSERT INTO DE VALUES(5, 8);

INSERT INTO DE VALUES(6, 9);
INSERT INTO DE VALUES(6, 11);
INSERT INTO DE VALUES(6, 12);

INSERT INTO DE VALUES(7, 10);
INSERT INTO DE VALUES(7, 11);
INSERT INTO DE VALUES(7, 12);

INSERT INTO DE VALUES(8, 1);
INSERT INTO DE VALUES(8, 3);
INSERT INTO DE VALUES(8, 12);

INSERT INTO DE VALUES(9, 1);
INSERT INTO DE VALUES(9, 3);
INSERT INTO DE VALUES(9, 12);

INSERT INTO DE VALUES(10, 13);
INSERT INTO DE VALUES(10, 14);

INSERT INTO DE VALUES(11, 12);


INSERT INTO PRODUCTEUR VALUES(1, 'Spielberg', 'Steven');
INSERT INTO PRODUCTEUR VALUES(2, 'Daniel', 'Sean');
INSERT INTO PRODUCTEUR VALUES(3, 'Productions', 'HBO');
INSERT INTO PRODUCTEUR VALUES(4, 'Rochant', 'Eric');
INSERT INTO PRODUCTEUR VALUES(5, 'Productions', '4 mecs en Baskets');
INSERT INTO PRODUCTEUR VALUES(6, 'Productions', 'Universal');
INSERT INTO PRODUCTEUR VALUES(7, 'Engine', 'Twin');
INSERT INTO PRODUCTEUR VALUES(8, 'Minami', 'Masahiko');
INSERT INTO PRODUCTEUR VALUES(9, 'Ikeguchi', 'Kazuhiko');
INSERT INTO PRODUCTEUR VALUES(10, 'Michels', 'Pete');
INSERT INTO PRODUCTEUR VALUES(11, 'Archer', 'Wes');
INSERT INTO PRODUCTEUR VALUES(12, 'Groening', 'Matt');

INSERT INTO PRODUIT VALUES(1, 2);
INSERT INTO PRODUIT VALUES(2, 3);
INSERT INTO PRODUIT VALUES(3, 4);
INSERT INTO PRODUIT VALUES(4, 5);
INSERT INTO PRODUIT VALUES(5, 6);
INSERT INTO PRODUIT VALUES(6, 7);
INSERT INTO PRODUIT VALUES(7, 8);
INSERT INTO PRODUIT VALUES(7, 9);
INSERT INTO PRODUIT VALUES(8, 10);
INSERT INTO PRODUIT VALUES(8, 11);
INSERT INTO PRODUIT VALUES(9, 12);
INSERT INTO PRODUIT VALUES(10, 1);
INSERT INTO PRODUIT VALUES(11, 1);
